name: CI

on:
  pull_request:
    types: [opened,reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke CircleCI PR Workflow
        env:
          PROJECT_SLUG: gh/hail-insta/terraform-provider-instaclustr
        run: |
          curl -X POST \
          -H 'Circle-Token: ${{ secrets.CIRCLE_TOKEN }}' \
          -d '{"branch":"${GITHUB_REF##*/}", "parameters":{"is-pr":true}}' \
          https://circleci.com/api/v2/project/${PROJECT_SLUG}/pipeline
